# -*- coding: utf-8 -*-
"""Reto 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XkyES79iuWDJwrDNrktl50YSG8h-DkhJ
"""

N, K = input().split() 
N = int(N)
K = int(K)
n = input().split()

exam = [int(i) for i in n]
exam_recordado = []
exam_revisados = []
copia_total = 0
copia_prof = 0

for i in exam:
  exam_revisado = i
  
  if exam_revisado in exam_revisados:
    copia_total += 1
  
  exam_revisados.append(i)

  if exam_revisado in exam_recordado:
    copia_prof += 1
  
  exam_recordado.append(exam_revisado)

  if len(exam_recordado) == (K + 1):
    exam_recordado.pop(0)
  
print(copia_total, copia_prof)

